# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/tecno/LD7/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/tecno/LD7

PRODUCT_COPY_FILES += \
    vendor/tecno/LD7/proprietary/lib64/libaptXHD_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptXHD_encoder.so \
    vendor/tecno/LD7/proprietary/lib64/libaptX_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptX_encoder.so \
        vendor/tecno/LD7/proprietary/data/camera/model/M_Segment_DoubleLoss_V1.model:$(TARGET_COPY_OUT_SYSTEM)/data/camera/model/M_Segment_DoubleLoss_V1.model \
    vendor/tecno/LD7/proprietary/data/camera/model/eyes_detect_model:$(TARGET_COPY_OUT_SYSTEM)/data/camera/model/eyes_detect_model \
    vendor/tecno/LD7/proprietary/data/camera/model/facerecheck.bin:$(TARGET_COPY_OUT_SYSTEM)/data/camera/model/facerecheck.bin \
    vendor/tecno/LD7/proprietary/data/camera/model/facerecheck.param:$(TARGET_COPY_OUT_SYSTEM)/data/camera/model/facerecheck.param \
    vendor/tecno/LD7/proprietary/data/camera/model/lightforgender_addindian_tf113_test5.tflite:$(TARGET_COPY_OUT_SYSTEM)/data/camera/model/lightforgender_addindian_tf113_test5.tflite \
    vendor/tecno/LD7/proprietary/data/camera/model/lightforgenderandage_tf113_test4.tflite:$(TARGET_COPY_OUT_SYSTEM)/data/camera/model/lightforgenderandage_tf113_test4.tflite \
    vendor/tecno/LD7/proprietary/data/camera/model/scene.tflite:$(TARGET_COPY_OUT_SYSTEM)/data/camera/model/scene.tflite \
    vendor/tecno/LD7/proprietary/data/camera/model/segment.tflite:$(TARGET_COPY_OUT_SYSTEM)/data/camera/model/segment.tflite \
    vendor/tecno/LD7/proprietary/data/camera/model/segmentPre.tflite:$(TARGET_COPY_OUT_SYSTEM)/data/camera/model/segmentPre.tflite \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_1184x1184.nv21:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_1184x1184.nv21 \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_1184x1184.yuyv:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_1184x1184.yuyv \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_1280x720.nv21:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_1280x720.nv21 \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_1280x720.yuyv:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_1280x720.yuyv \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_1312x576.nv21:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_1312x576.nv21 \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_1312x576.yuyv:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_1312x576.yuyv \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_1600x1200.nv21:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_1600x1200.nv21 \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_1600x1200.yuyv:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_1600x1200.yuyv \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_1920x1080.nv21:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_1920x1080.nv21 \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_1920x1080.yuyv:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_1920x1080.yuyv \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_2432x2432.nv21:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_2432x2432.nv21 \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_2432x2432.yuyv:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_2432x2432.yuyv \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_2560x1440.nv21:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_2560x1440.nv21 \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_2560x1440.yuyv:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_2560x1440.yuyv \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_2624x1152.nv21:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_2624x1152.nv21 \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_2624x1152.yuyv:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_2624x1152.yuyv \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_3264x2448.nv21:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_3264x2448.nv21 \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_3264x2448.yuyv:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_3264x2448.yuyv \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_3456x3456.nv21:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_3456x3456.nv21 \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_3456x3456.yuyv:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_3456x3456.yuyv \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_3840x2160.nv21:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_3840x2160.nv21 \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_3840x2160.yuyv:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_3840x2160.yuyv \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_4592x2016.nv21:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_4592x2016.nv21 \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_4592x2016.yuyv:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_4592x2016.yuyv \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_4608x3456.nv21:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_4608x3456.nv21 \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_4608x3456.yuyv:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_4608x3456.yuyv \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_640x480.nv21:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_640x480.nv21 \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_640x480.yuyv:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_640x480.yuyv \
    vendor/tecno/LD7/proprietary/data/camera/watermark/watermark_config:$(TARGET_COPY_OUT_SYSTEM)/data/camera/watermark/watermark_config \
    vendor/tecno/LD7/proprietary/bin/kpoc_charger:$(TARGET_COPY_OUT_SYSTEM)/bin/kpoc_charger \
    vendor/tecno/LD7/proprietary/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_SYSTEM)/firmware/BT_FW.cfg \
    vendor/tecno/LD7/proprietary/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_SYSTEM)/firmware/BT_FW.cfg \
    vendor/tecno/LD7/proprietary/firmware/Conf_MultipleTest.ini:$(TARGET_COPY_OUT_SYSTEM)/firmware/Conf_MultipleTest.ini \
    vendor/tecno/LD7/proprietary/firmware/WIFI_RAM_CODE_soc1_0_1a_1.bin:$(TARGET_COPY_OUT_SYSTEM)/firmware/WIFI_RAM_CODE_soc1_0_1a_1.bin \
    vendor/tecno/LD7/proprietary/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_SYSTEM)/firmware/WMT_SOC.cfg \
    vendor/tecno/LD7/proprietary/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_SYSTEM)/firmware/fm_cust.cfg \
    vendor/tecno/LD7/proprietary/firmware/focaltech_ts_fw.bin:$(TARGET_COPY_OUT_SYSTEM)/firmware/focaltech_ts_fw.bin \
    vendor/tecno/LD7/proprietary/firmware/gt1151_default_firmware1.img:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt1151_default_firmware1.img \
    vendor/tecno/LD7/proprietary/firmware/gt1151_default_firmware2.img:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt1151_default_firmware2.img \
    vendor/tecno/LD7/proprietary/firmware/gt1151_default_firmware3.img:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt1151_default_firmware3.img \
    vendor/tecno/LD7/proprietary/firmware/gt1151_default_firmware4.img:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt1151_default_firmware4.img \
    vendor/tecno/LD7/proprietary/firmware/gt1151_hotknot_auth_firmware1.img:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt1151_hotknot_auth_firmware1.img \
    vendor/tecno/LD7/proprietary/firmware/gt1151_hotknot_auth_firmware2.img:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt1151_hotknot_auth_firmware2.img \
    vendor/tecno/LD7/proprietary/firmware/gt1151_hotknot_auth_firmware3.img:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt1151_hotknot_auth_firmware3.img \
    vendor/tecno/LD7/proprietary/firmware/gt1151_hotknot_auth_firmware4.img:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt1151_hotknot_auth_firmware4.img \
    vendor/tecno/LD7/proprietary/firmware/gt1151_patch_jump_firmware1.img:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt1151_patch_jump_firmware1.img \
    vendor/tecno/LD7/proprietary/firmware/gt1151_patch_jump_firmware2.img:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt1151_patch_jump_firmware2.img \
    vendor/tecno/LD7/proprietary/firmware/gt1151_patch_jump_firmware3.img:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt1151_patch_jump_firmware3.img \
    vendor/tecno/LD7/proprietary/firmware/gt1151_patch_jump_firmware4.img:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt1151_patch_jump_firmware4.img \
    vendor/tecno/LD7/proprietary/firmware/gt9886_cfg_6785v96.bin:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt9886_cfg_6785v96.bin \
    vendor/tecno/LD7/proprietary/firmware/gt9886_cfg_6785v99.bin:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt9886_cfg_6785v99.bin \
    vendor/tecno/LD7/proprietary/firmware/gt9886_cfg_6885v1.bin:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt9886_cfg_6885v1.bin \
    vendor/tecno/LD7/proprietary/firmware/gt9886_firmware_6785a4.bin:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt9886_firmware_6785a4.bin \
    vendor/tecno/LD7/proprietary/firmware/gt9886_firmware_6785ae.bin:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt9886_firmware_6785ae.bin \
    vendor/tecno/LD7/proprietary/firmware/gt9886_firmware_6885a1.bin:$(TARGET_COPY_OUT_SYSTEM)/firmware/gt9886_firmware_6885a1.bin \
    vendor/tecno/LD7/proprietary/firmware/mt6631_fm_v1_coeff.bin:$(TARGET_COPY_OUT_SYSTEM)/firmware/mt6631_fm_v1_coeff.bin \
    vendor/tecno/LD7/proprietary/firmware/mt6631_fm_v1_patch.bin:$(TARGET_COPY_OUT_SYSTEM)/firmware/mt6631_fm_v1_patch.bin \
    vendor/tecno/LD7/proprietary/firmware/novatek_ts_fw.bin:$(TARGET_COPY_OUT_SYSTEM)/firmware/novatek_ts_fw.bin \
    vendor/tecno/LD7/proprietary/firmware/novatek_ts_mp.bin:$(TARGET_COPY_OUT_SYSTEM)/firmware/novatek_ts_mp.bin \
    vendor/tecno/LD7/proprietary/firmware/soc1_0_patch_mcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_SYSTEM)/firmware/soc1_0_patch_mcu_1a_1_hdr.bin \
    vendor/tecno/LD7/proprietary/firmware/soc1_0_ram_bt_1a_1_hdr.bin:$(TARGET_COPY_OUT_SYSTEM)/firmware/soc1_0_ram_bt_1a_1_hdr.bin \
    vendor/tecno/LD7/proprietary/firmware/soc1_0_ram_mcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_SYSTEM)/firmware/soc1_0_ram_mcu_1a_1_hdr.bin \
    vendor/tecno/LD7/proprietary/firmware/soc1_0_ram_wifi_1a_1_hdr.bin:$(TARGET_COPY_OUT_SYSTEM)/firmware/soc1_0_ram_wifi_1a_1_hdr.bin \
    vendor/tecno/LD7/proprietary/firmware/wifi.cfg:$(TARGET_COPY_OUT_SYSTEM)/firmware/wifi.cfg \
    vendor/tecno/FULL-64/proprietary/vendor/fstab.enableswap:$(TARGET_COPY_OUT_SYSTEM)/fstab.enableswap \
    vendor/tecno/LD7/proprietary/etc/init/kpoc_charger.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/kpoc_charger.rc \
    vendor/tecno/LD7/proprietary/etc/wifi/wpa_supplicant.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/wpa_supplicant.conf \
    vendor/tecno/LD7/proprietary/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/tecno/LD7/proprietary/etc/wifi/wpa_supplicant_overlay.conf$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/tecno/LD7/proprietary/lib/libshowlogo.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libshowlogo.so \
    vendor/tecno/LD7/proprietary/etc/init/android.hardware.keymaster@4.0-service.beanpod.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/android.hardware.keymaster@4.0-service.beanpod.rc
